services:
  ccd:
    build: .
    container_name: ccd_container
    ports:
        - protocol: udp
          target: 10011
          published: 10013
          mode: host
    volumes:
      - .:/ccd
    restart: always